### ISSUE TITLE
Why Append Ref Link to Head?

### ISSUE THREAD

**Issue by yuens1002** [rnicholus/web-components-loader#14]
hi there, i noticed in the example, the web-component (WC) ref tag is appended to the body...
`document.body.appendChild(importEl)`

from a number of documentation i've read, WC ref tags are usually in the head tag. So i guess, the question is really why append to document.body?

**Comment by rnicholus** [comment]
I honestly can't remember why i decided to append this to `<body>`. Is this causing an issue for you?

**Comment by yuens1002** [comment]
thanks for your reply, but i can't seem to use your example code with
webpack 4. so i tried to modify the simplest example given from the repo to
the following...

module: {
    rules: [
      {
        test: /\.html$/,
        use: [
          // apply multiple loaders and options
          "web-components-loader",
          {
            loader: "web-components-loader"
          }
        ]
      },
    ]
  }

and got the following error

ERROR in ./node_modules/bosonic-core-elements/src/b-accordion.html
Module build failed: TypeError: Cannot read property 'output' of undefined
    at Object.module.exports
(/Users/sunny/web-component/node_modules/web-components-loader/lib/index.js:27:6
8)
 @ ./src/index.js 6:0-85 10:16-28

**Comment by rnicholus** [comment]
I’m not surprised this doesn’t work with recent versions of webpack. I created this as part of an experiment a while back which I’ve since abandoned.

**Comment by anastasiap** [comment]
It'd be nice if there was some sort of flag saying that it's not working any more. Just to save time for others.
